version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "8051:8050"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data  # Optional: for external data files
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
